name: Swift Package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  macos:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4
      - name: Swift build
        run: swift build
      - name: Swift test
        run: swift test
